# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 'Blog'
    identifier: 'blog-top-menu'
    weight: 20
  - name: 'New posts'
    url: '/post/'
    parent: 'blog-top-menu'
  - name: 'Top posts'
    url: '#top-posts'
    parent: 'blog-top-menu'
  - name: 'Topic list'
    url: '#tags'
    parent: 'blog-top-menu'
  - name: 'Podcasts'
    identifier: 'podcast-top-menu'
    weight: 25
  - name: 'ATC Doublecut with Micah Woods'
    url: 'https://doublecut.asianturfgrass.com/'
    parent: 'podcast-top-menu'
  - name: 'ATC Office Hours'
    url: 'https://office-hours.asianturfgrass.com/'
    parent: 'podcast-top-menu'
  - name: 'Research'
    weight: 50
    identifier: 'research-top-menu'
  - name: 'Projects'
    url: '#projects'
    parent: 'research-top-menu'
  - name: 'Library'
    url: '#publications'
    parent: 'research-top-menu'
  - name: 'Shiny Apps'
    url: '/shiny-apps'
    parent: 'research-top-menu'
  - name: 'ClipVol'
    url: '/project/clipvol/'
    parent: 'research-top-menu'
  - name: 'Soil tests'
    weight: 40
    identifier: 'soil-top-menu'
  - name: 'MLSN'
    url: '/mlsn/'
    parent: 'soil-top-menu'
  - name: 'OM246'
    url: '/project/om246/'
    parent: 'soil-top-menu'
  - name: 'Soil tests and other lab services'
    url: '/project/soil-tests/'
    parent: 'soil-top-menu'
  - name: 'Newsletters'
    url: '#newsletters'
    weight: 55
  - name: 'About'
    url: '#about'
    identifier: 'about'
  - name: 'About'
    url: '#about'
    parent: 'about'
  - name: 'Contact'
    url: '#contact'
    parent: 'about'
  - name: 'PACE Turf'
    url: 'https://www.paceturf.org/'
    parent: 'about'

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
