# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: m

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'Asian Turfgrass Center'
    description: 'ATC was founded by Dr. Micah Woods in 2006 and now researches and shares practical information about turfgrass selection and management.'
    twitter: 'asianturfgrass'
  analytics:
    google_analytics: 'UA-83670583-1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

i_am_a_sponsor: true

footer:
  copyright:
    notice: '© 2006--{year} [Asian Turfgrass Center](https://www.asianturfgrass.com/). This site made with [Wowchemy](https://wowchemy.com/) & [Hugo](https://gohugo.io/).'


# Localization

locale:
  date_format: '2006-01-02'
  time_format: '15:04'
  address_format: en-us

# Site features

pager: true
show_related: true

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search: 
    provider: algolia
    algolia:
      app_id: 'IIVNQT87S5'
      api_key: '97eaa6e0ca2f48a52bd5cb4b45a5e721'
      index_name: 'netlify_42333bde-3158-439e-9846-64e6abf25f0c_master_all'
      show_logo: true
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
